Add documentation for Globalize
consul/docs pull request #53
Opened 2018-04-19 14:30 UTC by iagirre

References
==========
Related issue: https://github.com/consul/consul/issues/2436

Objectives
==========
This PR adds the necessary documentantion to make any attribute of any model translatable. It explains the procedure step by step with examples of code.

The documentation is in spanish and english.

2018-04-20 08:11 UTC, bertocq requested changes
Really awesome to get this documented both for future PR's in consul and for the forks that will do their own custom models 👏 

Just two typos and we're good to merge!

2018-04-20 08:11 UTC, bertocq commented on en/features/globalize.md
> +Add the `Translatable` module in the controller that will handle the traduccions.
`traduccions` => `translations`

2018-04-20 08:11 UTC, bertocq commented on en/features/globalize.md
> +class Post < Admin::BaseController
it should be `PostsController` not `Post`, this is not the model

2018-04-20 08:23 UTC, bertocq commented on en/features/globalize.md
> +We also need to add the option `globalize_accessors` to include all the locales we want to support. This gem generates all the methods needed by the application (`title_en`, `title_es`, etc.).
I would mention that as the documentation says at https://github.com/globalize/globalize-accessors#example.

> Calling globalize_accessors with no options will therefore generate accessor methods for all translated fields and available languages.

In case you don't want to explicitly include all available languages on every translatable model... and having to increase/decrease that list every time you add/remove support for one. This should be only used in case the list you're going to specify is smaller than the list of total supported languages.

2018-04-20 09:58 UTC, iagirre commented
I've corrected both typos and included that piece of information about the `globalize_accessors` without any option :)

2018-05-09 12:37 UTC, voodoorai2000 commented
Excellent! 🎉

2018-05-09 12:37 UTC, merged